[[warp_account]]
private_key = "iIT7Bt4t6Kh2RxtbU1mpZFGmEce1LyjDx7SCpr7KDV4="
public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
reserved = "gmY9" # [130, 102, 61]
local_address = ["172.16.0.2/32", "2606:4700:110:8ae5:7239:b559:a92e:7797/128"]
fake_packets = "5-10"

[[warp_account]]
private_key = "yHqBTucGPz22CGKfOORyYNild2ADpXVmKSU66j7HFWM="
public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
reserved = "m/tH" # [155, 251, 71]
local_address = ["172.16.0.2/32", "2606:4700:110:8ab7:4964:ba17:eb98:c50c/128"]
fake_packets = "5-10"